### ISSUE TITLE
Question about model size

### ISSUE THREAD

**Issue by krummrey** [omidsakhi/lorakit#2]
Hi,
the size of the lora created is 11.8mb, which seems smaller than most other loras out there. Is there a way to control how many features the lora will pick up?
In general, could you elaborate a little more on the options one has over training?
Great work btw, it runs on colab free. Slow, but it runs. I got 800 steps before getting kicked out.

To make resuming easier fot others, maybe add this little hint in the sample config.
`#resume_from_checkpoint: ""       #"mylora_1.0_0000000800" to resume after step 800`

**Comment by omidsakhi** [comment]
Rank of the lora has a direct effect on the size. The default size is 4. Maybe try to increase lora's rank.
